### ISSUE TITLE
Discussion regarding layout of template JSON Editors

### ISSUE THREAD

**Issue by abhi211199** [moja-global/GSoC.FLINT.JSON_Interface#14]
This issue is regarding discussion for the layout of the form-like JSON Editor.
@mfellows, can you please verify the points and clear my doubts, which will help in creating the layout of the editor smoothly!

### Libraries (Will be provided in each file)
UX: 
- A [Switch](https://material-ui.com/components/switches/)(default set to `false`)
- When clicked, user can add `library` key with value either **internal or external**
- User will have option to add/remove multiple libraries.

### Localdomain
UX:
- `start_date` : [`DatePicker`](https://material-ui.com/components/pickers/#date-time-pickers)
- `end_date` : `DatePicker`
- `landUnitBuildSuccess` : `landUnitBuildSuccess` (will be set by default but user will have option to edit)
- `simulateLandUnit` : `simulateLandUnit` (will be set by default but user will have option to edit)
- `sequencer_library` : `moja.modules.cbm` (will be set by default but user will have option to edit)
- `sequencer` : `CBMSequencer`  (will be set by default but user will have option to edit)
- `timing` : `annual` set as default, drop-down list will be provided with options being `annual, monthly, daily`
- `type` : `spatial_tiled` set as default, drop-down list will be provided with options being `spatially_referenced_sql, spatially_referenced_nosql, threaded_spatially_referenced_nosql`
- `landscape` :
``` json
{
            "provider": "RasterTiled",
            "num_threads": 4,
            "tiles": [],
            "x_pixels": 1000,
            "y_pixels": 1000,
            "tile_size_x": 1.0,
            "tile_size_y": 1.0
}
```
This is not user-editable

### Variables: A `Variables` key may  contain three types of key, `an initial value(read/write), a transform or FlintData object(read only)`
UX:
- Key-value pairs of all the `initial values` like "enable_peatland", "enable_moss" etc will be provided in a **collapsable bar**(as the form is expected to be a long one"
- Widely used `FlintData` configuration will be provided, which can be chosen by users.
- `Transforms` can be chosen and a temlate block will be added and can be edited by user.

### Variables: 
- [x] Are there any specific `FlintData` configurations or any new configuration may be written by user?
- [x] In `LocationIdxFromFlintDataTransform`
```json
"initial_age": {
    "transform": {
        "library": "internal.flint",
        "type": "LocationIdxFromFlintDataTransform",
        "provider": "RasterTiled",
        "data_id": "initial_age"
    }
},
```
- Does the choices for `library` field ranges between `internal.flint`  and `external.flint` or something other than that?
- Are there any pre-defined choices for `provider` field(I read that these values are fetched from provider_config.json?
- Can you provide some information about how should I implement `data_id` key?
- Are there any list of classifiers used in `vars` key in `CompositeTransform`?

- [x] Can the user insert other keys in the transform block other than `library, type, provider, data_id`?(Just to confirm coz it can be done in SQLQueryTransform, as is written in doc)

**Comment by mfellows** [comment]
1) _Are there any specific FlintData configurations or any new configuration may be written by user?_
There are a few built-in types, but the configuration options can vary a lot, so I think for now we should leave the editing for FlintData pretty generic - it will always have the "type", "library", and "settings" keys, where "type" and "library" are always string values (but too many possibilities to be drop-downs), and "settings" should just be a raw JSON editor.

2) _In LocationIdxFromFlintDataTransform ..._
- library is always internal.flint (no other option)

- no pre-defined choices for the provider field, although it does have to match a key in the "Providers" section in provider_config.json - often scripts are used to fill in the details of provider_config.json though, so the editor tool shouldn't require that a matching key exists

- data_id is always a string value that must match the name of an item in the "layers" section of a spatial provider in provider_config.json - but this is another instance of where provider_config.json is often filled in by other scripts at a later time, so the JSON editor shouldn't require a match. An example would be:

`"initial_age": {
    "transform": {
        "library": "internal.flint",
        "type": "LocationIdxFromFlintDataTransform",
        "provider": "RasterTiled",
        "data_id": "initial_age"
    }
},`

`{
    "Providers": {
        "RasterTiled": {
            "layers": [
                {
                    "name": "initial_age",
                    "layer_path": "..\\layers\\tiled\\initial_age_moja.tiff",
                    "layer_prefix": "initial_age_moja"
                }
            ]
        }
    }
}`

Where data_id = "initial_age" matches name = "initial_age".

- The vars list in a CompositeTransform contains the names of one or more keys in the "Variables" section(s) of the config files in a project - since the "Variables" sections are always changing, there are no predefined choices for this - it would be useful to present the user with a list of discovered names though (the first-level keys in all the "Variables" sections in the current set of files)

3) _Can the user insert other keys in the transform block other than library, type, provider, data_id?(Just to confirm coz it can be done in SQLQueryTransform, as is written in doc)_
The common keys are really just library and type; provider and data_id are specific to a few transforms: SQLQueryTransform, LocationIdxFromFlintDataTransform - other types of transforms could add other arbitrary keys, so there should be a way for the user to enter additional keys and values an addition to the keys pre-populated by the template

**Comment by abhi211199** [comment]
@mfellows sir, thanks for the information. I will create an initial layout of the editor in 2-3 days.
